server:
  port: 8082
spring:
  application:
    name: JourneyGateway
  cloud:
    gateway: # 网关
      actuator:
        verbose:
          enabled: true
      globalcors:
        cors-configurations: # 跨域配置
          '[/**]':
            allowedHeaders: "*"
            allowCredentials: true
            allowedOrigins: "*"  # http://192.168.16.115:8082,http:localhost:8082
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

      # 路由负载配置
      default-filters:
      routes:
        - id: my_course # 测试服务入口
          # uri: http://localhost:8083/ # http://localhost:8082/course/doc.html
          uri: lb://load-course-service # http://localhost:8082/course/doc.html
          predicates:
            - Path=/course/**

        - id: my_mine # 关于我的服务入口
          uri: http://localhost:8084/ # http://localhost:8082/mine/doc.html
          predicates:
            - Path=/mine/**

load-course-service: # 负载均衡-测试服务的
  ribbon:
    listOfServers: localhost:8083 # 负载地址 - 轮询到多个地址 localhost:8083, localhost:8084
    # 负载轮询策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    # 健康检查
    # NFLoadBalancerPingClassName: com.modules.scistor.config.HealthExamination

ribbon: # 有负载均衡的时候需要将服务与注册关闭
  eureka:
    enabled: false # 必须要关闭eureka的服务注册与发现

# 服务注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true

# 熔断
feign:
  hystrix:
    enabled: true

# 日志
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug




