server:
  port: 8082
spring:
  application:
    name: JourneyGateway
  cloud:
    gateway: # 网关
      actuator:
        verbose:
          enabled: true
      globalcors: # 跨域配置
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      # 路由负载配置
      default-filters:
      routes:
        - id: my_route
          uri: lb://load-balanced-service
          predicates:
            - Path=/crs/**
          filters:
            - StripPrefix=1

load-balanced-service:
  ribbon:
    listOfServers: http://localhost:8072, http://localhost:8073  # 负载地址
    # 负载轮询策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    # 健康检查
    NFLoadBalancerPingClassName: com.modules.scistor.config.HealthExamination


# 服务注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
# 熔断
feign:
  hystrix:
    enabled: true


# 日志
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug




